name: Run on comment

on:
  issue_comment:
    types: [created]

jobs:
  echo-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Log Comment for PR
        if: github.event.issue.pull_request != null
        env:
          COMMENT: ${{ github.event.comment.body }}
        run: echo "This is a comment on a pull request! \$COMMENT"

      - name: Log Comment for Issue
        if: github.event.issue.pull_request == null
        env: 
          COMMENT: ${{ github.event.comment.body }}
          HELLO: WORLD
        run: echo "This is a comment on an issue! $HELLO"
